substitutions:
  _REGION: us-central1
  _REPO: model-trellis
  _TAG: ngc-candidate
  _CUDA_ARCH_LIST: "8.0;8.6;8.9;9.0+PTX"

steps:
  - id: build-portable-image
    name: gcr.io/cloud-builders/docker
    dir: workers/model-trellis
    args:
      - build
      - --build-arg
      - TORCH_CUDA_ARCH_LIST=${_CUDA_ARCH_LIST}
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:${_TAG}
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:latest
      - .

  - id: push-portable-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:${_TAG}

options:
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s

serviceAccount: projects/aerial-vehicle-466722-p5/serviceAccounts/three-ws-build@aerial-vehicle-466722-p5.iam.gserviceaccount.com
